import temp from "../assets/NavBar/Carry.svg";

var productsDummy = [
  {
    id: 1223561735867137,
    images: [temp],
    title: "Dot Grid Notebooks",
    price: "10.99",
    productType: "Dot Grid Notebooks",
    category: "Featured",
    subCategory: "A5",
    colours: [
      { code: "#0E2C77", name: "Blue" },
      { code: "#000000", name: "Black" },
      { code: "#B8B3B3", name: "Light Grey" },
      { code: "#304043", name: "Dark Grey" },
    ],
  },
  {
    id: 1223561735867138,
    images: [temp],
    title: "Dot Grid Notebooks - A4",
    price: "12.99",
    productType: "Dot Grid Notebooks",
    category: "Featured",
    subCategory: "A4",
    colours: [
      { code: "#0E2C77", name: "Blue" },
      { code: "#000000", name: "Black" },
      { code: "#B8B3B3", name: "Light Grey" },
      { code: "#304043", name: "Dark Grey" },
    ],
  },
  {
    id: 1223561735867139,
    images: [temp],
    title: "Lined Notebook Black Marble ",
    price: "18.89",
    productType: "Dot Grid Notebooks",
    category: "Featured",
    subCategory: "A5",
    colours: [
      { code: "#0E2C77", name: "Blue" },
      { code: "#000000", name: "Black" },
      { code: "#B8B3B3", name: "Light Grey" },
      { code: "#304043", name: "Dark Grey" },
    ],
  },
  {
    id: 1223561735867140,
    images: [temp],
    title: "Recycled Notebook Dark Green",
    price: "10.99",
    productType: "Lined Paper Notebooks",
    category: "Featured",
    subCategory: "A5",
    colours: [
      { code: "#0E2C77", name: "Blue" },
      { code: "#000000", name: "Black" },
      { code: "#B8B3B3", name: "Light Grey" },
      { code: "#304043", name: "Dark Grey" },
    ],
  },
  {
    id: 1223561735867141,
    images: [temp],
    title: "Recycled Paper Cover Notebook",
    price: "15.89",
    productType: "Lined Paper Notebooks",
    category: "Featured",
    subCategory: "A5",
    colours: [
      { code: "#0E2C77", name: "Blue" },
      { code: "#000000", name: "Black" },
      { code: "#B8B3B3", name: "Light Grey" },
      { code: "#304043", name: "Dark Grey" },
    ],
  },
  {
    id: 1223561735867142,
    images: [temp],
    title: "Recycled Lined Notebook Bright Yellow",
    price: "20.89",
    productType: "Dot Grid Notebooks",
    category: "New",
    subCategory: "A5",
    colours: [
      { code: "#0E2C77", name: "Blue" },
      { code: "#000000", name: "Black" },
      { code: "#B8B3B3", name: "Light Grey" },
      { code: "#304043", name: "Dark Grey" },
    ],
  },
  {
    id: 1,
    images: [temp],
    title: "Lined Notebook Black Marble ",
    price: "18.89",
    subCategory: "A5",
    category: "New",
    productType: "Lined Paper Notebooks",
    colours: [
      { code: "#6C6940", name: "Green" },
      { code: "#000000", name: "Black" },
    ],
  },
  {
    id: 2,
    images: [temp],
    title: "M16 Ballpoint Pen Refill",
    price: "15.99",
    category: "New",
    productType: "Popular Items",
    subCategory: "F,M,B",
    colours: [
      { code: "#0E2C77", name: "Blue" },
      { code: "#000000", name: "Black" },
    ],
  },
  {
    id: 3,
    images: [temp],
    title: "Recycled Lined Notebook Bright Yellow",
    price: "20.89",
    subCategory: "A5",
    category: "New",
    productType: "Lined Paper Notebooks",
    colours: [{ code: "#F6D324", name: "Yellow" }],
  },
];

export default productsDummy;